version: '2.1'
services:
  reservation:
    networks:
      - abc
    image: reservation
    container_name: "reservation"
    ports:
     - "6060:6060"
    links:
      - reservation-mysql
  reservation-mysql:
    networks:
      - abc
    image: mysql:5.7.17
    container_name: "reservation-mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DB=reservation
    ports:
      - "3309:3306"
networks:
  abc:
    external: true

